call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-sleuth'
Plug 'scrooloose/syntastic'

call plug#end()

syntax on
filetype plugin indent on

set showcmd
set hlsearch
set ignorecase
set smartcase
set number

set shiftwidth=4
set softtabstop=4
set expandtab

if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_right_sep = ''

let g:airline#extensions#syntastic#enabled = 1
let g:syntastic_html_tidy_exec = 'tidy'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_html_tidy_quiet_messages = { "level": "warnings" }
