call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/syntastic'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'Valloric/YouCompleteMe'
Plug 'lervag/vimtex'
Plug 'Yggdroot/indentLine'

call plug#end()

syntax on
filetype plugin indent on

set showcmd
set hlsearch
set ignorecase
set smartcase
set number
set list lcs=trail:·,tab:\ \ 
set mouse=a

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

set laststatus=2

if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_right_sep = ''

let g:airline#extensions#syntastic#enabled = 1
let g:syntastic_html_tidy_exec = 'tidy'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_html_tidy_quiet_messages = { "level": "warnings" }

let g:UltiSnipsExpandTrigger="<c-b>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0

" Vim
let g:indentLine_color_term = 239

" GVim
let g:indentLine_color_gui = '#A4E57E'

" none X terminal
let g:indentLine_color_tty_light = 7 " (default: 4)
let g:indentLine_color_dark = 1 " (default: 2)

hi linenr ctermfg=green ctermbg=black cterm=bold
set cursorline
hi cursorline cterm=none
hi cursorlinenr ctermfg=black ctermbg=green cterm=bold
